export { default as Login } from "./Auth/Login";
export { default as EmployeeStatistics } from "./Dashboard/Employee/EmployeeStatistics";
export { default as LettersPage } from "./Letters/LettersPage";
export { default as Calendar } from "./Calendar/CalendarStatistca";
export { default as GenStatistics } from "./Dashboard/DashboardStats/GenStatistics";
export { default as Dashboard } from "./Dashboard/DashboardPage/Dashboard";
export { default as UsersManagement} from "./UsersManagement/UsersManagement";
export { default as ProductManagement} from "./ProductManagement/ProductManagement";
export { default as TurnoverReport} from "./Reports/TurnoverReport/TurnoverReport";
export { default as GoodsBalanceReport} from "./Reports/GoodsMaterialsBalance/GoodsMaterialsBalance";
export { default as ReportTableOne} from "./Reports/ReportTable/ReportTableOne";
export { default as ReferenceRequisites } from "./Reference/Requisites/ReferenceRequisites";
export { default as Bank } from "./Reference/Bank/Bank";
export { default as Contracts } from "./Reference/Contracts/Contracts";
export { default as GoodsIn } from "./Reference/GoodsIn/GoodsIn";
export { default as GoodsOut } from "./Reference/GoodsOut/GoodsOut";
export { default as WareHouseTransfer } from "./Reference/WareHouseTransfer/WareHouseTransfer";
export { default as YearPlan } from "./Reference/YearPlan/YearPlan";